from typing import Dict, Any, Optional, List
from sqlalchemy.orm import Session
from pydantic import BaseModel, Field

from app.ai.tools.base_tool import AITool, ToolPermissionLevel
from app.services.procurement_service import procurement_service
from app.models.purchase_order import PurchaseOrder

class CreatePurchaseOrderInput(BaseModel):
    supplier_id: int = Field(..., description="ID of supplier to issue order to")
    items: List[Dict[str, Any]] = Field(..., description="List of items: [{'product_id': int, 'quantity': int, 'unit_cost': float}]")
    notes: str = Field("Generated by Autonomous Procurement Agent", description="Order notes")

class ApprovePurchaseOrderInput(BaseModel):
    po_id: int = Field(..., description="ID of purchase order to approve")

class GetOpenPurchaseOrdersTool(AITool):
    name = "get_open_purchase_orders"
    description = "List all active, pending approval, or sent purchase orders."
    permission_level = ToolPermissionLevel.READ

    def execute(self, db: Session, user: Optional[Any] = None, organization_id: int = 1, **kwargs) -> Dict[str, Any]:
        pos = db.query(PurchaseOrder).filter(
            PurchaseOrder.organization_id == organization_id,
            PurchaseOrder.status.in_(["draft", "pending_approval", "approved", "sent"])
        ).order_by(PurchaseOrder.created_at.desc()).all()

        return {
            "total_open_orders": len(pos),
            "orders": [
                {
                    "id": p.id,
                    "po_number": p.po_number,
                    "supplier_id": p.supplier_id,
                    "status": p.status,
                    "total_cost": p.total_cost,
                    "created_at": p.created_at.isoformat() if p.created_at else None
                }
                for p in pos
            ]
        }

class CreatePurchaseOrderTool(AITool):
    name = "create_purchase_order"
    description = "Create a real Purchase Order in DRAFT or PENDING_APPROVAL status following AI recommendation."
    input_schema = CreatePurchaseOrderInput
    permission_level = ToolPermissionLevel.WRITE

    def execute(self, db: Session, user: Optional[Any] = None, organization_id: int = 1, **kwargs) -> Dict[str, Any]:
        if not self.check_authorization(user):
            return {"success": False, "error": "Unauthorized: Only managers and admins can execute purchase order creation."}

        params = self.validate_inputs(**kwargs)
        user_email = getattr(user, "email", "ai_agent@emox.ai")

        po = procurement_service.create_purchase_order(
            db=db,
            organization_id=organization_id,
            supplier_id=params["supplier_id"],
            items=params["items"],
            notes=params.get("notes", ""),
            created_by=f"AI Agent (Authorized by {user_email})",
            initial_status="pending_approval"
        )

        self.audit_execution(
            db=db,
            user=user,
            organization_id=organization_id,
            action="PO_CREATED",
            entity="PurchaseOrder",
            entity_id=po.id,
            details={"po_number": po.po_number, "total_cost": po.total_cost}
        )

        return {
            "success": True,
            "po_id": po.id,
            "po_number": po.po_number,
            "status": po.status,
            "total_cost": po.total_cost,
            "message": f"Purchase Order {po.po_number} created in PENDING_APPROVAL status."
        }

class ApprovePurchaseOrderTool(AITool):
    name = "approve_purchase_order"
    description = "Authorize and approve an existing purchase order for dispatch."
    input_schema = ApprovePurchaseOrderInput
    permission_level = ToolPermissionLevel.WRITE

    def execute(self, db: Session, user: Optional[Any] = None, organization_id: int = 1, **kwargs) -> Dict[str, Any]:
        if not self.check_authorization(user):
            return {"success": False, "error": "Unauthorized: Requires manager or admin role to approve orders."}

        params = self.validate_inputs(**kwargs)
        user_email = getattr(user, "email", "manager@emox.ai")

        po = procurement_service.approve_purchase_order(
            db=db,
            organization_id=organization_id,
            po_id=params["po_id"],
            approved_by=user_email
        )

        return {
            "success": True,
            "po_id": po.id,
            "po_number": po.po_number,
            "status": po.status,
            "approved_by": po.approved_by
        }
