"""initial_schema

Revision ID: 5ac561c16a72
Revises: 
Create Date: 2026-09-07 20:38:13.439975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac561c16a72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('reserved_stock', sa.Integer(), server_default='0', nullable=False))
    op.add_column('inventory', sa.Column('safety_stock', sa.Integer(), server_default='10', nullable=False))
    op.add_column('inventory', sa.Column('last_restocked_at', sa.DateTime(), nullable=True))
    op.add_column('inventory', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.create_unique_constraint(None, 'inventory', ['product_id'])
    op.drop_constraint(op.f('inventory_product_id_fkey'), 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'inventory', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(), server_default='Standard', nullable=True))
    op.add_column('products', sa.Column('cost_price', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('products', sa.Column('status', sa.String(), server_default='active', nullable=False))
    op.add_column('products', sa.Column('reorder_point', sa.Integer(), server_default='15', nullable=False))
    op.add_column('products', sa.Column('safety_stock', sa.Integer(), server_default='10', nullable=False))
    op.add_column('products', sa.Column('lead_time_days', sa.Integer(), server_default='5', nullable=False))
    op.add_column('products', sa.Column('specifications', sa.Text(), server_default='{}', nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.add_column('sales', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('unit_price', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('sales', sa.Column('total_amount', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('sales', sa.Column('currency', sa.String(), server_default='INR', nullable=False))
    op.add_column('sales', sa.Column('transaction_ref', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.drop_constraint(op.f('sales_product_id_fkey'), 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sales', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    op.add_column('suppliers', sa.Column('reliability_score', sa.Float(), server_default='92.0', nullable=False))
    op.add_column('suppliers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('address', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('category', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('status', sa.String(), server_default='active', nullable=False))
    op.add_column('suppliers', sa.Column('overall_score', sa.Float(), server_default='88.0', nullable=False))
    op.add_column('suppliers', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('suppliers', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_column('suppliers', 'updated_at')
    op.drop_column('suppliers', 'created_at')
    op.drop_column('suppliers', 'overall_score')
    op.drop_column('suppliers', 'status')
    op.drop_column('suppliers', 'category')
    op.drop_column('suppliers', 'address')
    op.drop_column('suppliers', 'phone')
    op.drop_column('suppliers', 'email')
    op.drop_column('suppliers', 'reliability_score')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key(op.f('sales_product_id_fkey'), 'sales', 'products', ['product_id'], ['id'])
    op.drop_column('sales', 'created_at')
    op.drop_column('sales', 'transaction_ref')
    op.drop_column('sales', 'currency')
    op.drop_column('sales', 'total_amount')
    op.drop_column('sales', 'unit_price')
    op.drop_column('sales', 'order_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.alter_column('products', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'specifications')
    op.drop_column('products', 'lead_time_days')
    op.drop_column('products', 'safety_stock')
    op.drop_column('products', 'reorder_point')
    op.drop_column('products', 'status')
    op.drop_column('products', 'cost_price')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'category_id')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_product_id_fkey'), 'inventory', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'inventory', type_='unique')
    op.drop_column('inventory', 'updated_at')
    op.drop_column('inventory', 'last_restocked_at')
    op.drop_column('inventory', 'safety_stock')
    op.drop_column('inventory', 'reserved_stock')
    op.drop_column('inventory', 'warehouse_id')
    # ### end Alembic commands ###
