"""create_organizations_and_tenant_scoping

Revision ID: 8ffd29629b16
Revises: eeae576435ad
Create Date: 2026-09-08 15:49:27.277430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ffd29629b16'
down_revision: Union[str, Sequence[str], None] = 'eeae576435ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('organization_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_memberships_id'), 'organization_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_organization_id'), 'organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False)
    op.add_column('ai_audit_logs', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ai_audit_logs_organization_id'), 'ai_audit_logs', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'ai_audit_logs', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('ai_conversations', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ai_conversations_organization_id'), 'ai_conversations', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'ai_conversations', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('ai_jobs', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ai_jobs_organization_id'), 'ai_jobs', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'ai_jobs', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('ai_recommendations', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ai_recommendations_organization_id'), 'ai_recommendations', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'ai_recommendations', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('inventory', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inventory_organization_id'), 'inventory', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'inventory', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('inventory_alerts', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inventory_alerts_organization_id'), 'inventory_alerts', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'inventory_alerts', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('knowledge_documents', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_knowledge_documents_organization_id'), 'knowledge_documents', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_documents', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('products', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'products', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('purchase_orders', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchase_orders_organization_id'), 'purchase_orders', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'purchase_orders', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('sales', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sales_organization_id'), 'sales', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('suppliers', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_suppliers_organization_id'), 'suppliers', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'suppliers', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_index(op.f('ix_suppliers_organization_id'), table_name='suppliers')
    op.drop_column('suppliers', 'organization_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_organization_id'), table_name='sales')
    op.drop_column('sales', 'organization_id')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_orders_organization_id'), table_name='purchase_orders')
    op.drop_column('purchase_orders', 'organization_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_column('products', 'organization_id')
    op.drop_constraint(None, 'knowledge_documents', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_documents_organization_id'), table_name='knowledge_documents')
    op.drop_column('knowledge_documents', 'organization_id')
    op.drop_constraint(None, 'inventory_alerts', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_alerts_organization_id'), table_name='inventory_alerts')
    op.drop_column('inventory_alerts', 'organization_id')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_organization_id'), table_name='inventory')
    op.drop_column('inventory', 'organization_id')
    op.drop_constraint(None, 'ai_recommendations', type_='foreignkey')
    op.drop_index(op.f('ix_ai_recommendations_organization_id'), table_name='ai_recommendations')
    op.drop_column('ai_recommendations', 'organization_id')
    op.drop_constraint(None, 'ai_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_ai_jobs_organization_id'), table_name='ai_jobs')
    op.drop_column('ai_jobs', 'organization_id')
    op.drop_constraint(None, 'ai_conversations', type_='foreignkey')
    op.drop_index(op.f('ix_ai_conversations_organization_id'), table_name='ai_conversations')
    op.drop_column('ai_conversations', 'organization_id')
    op.drop_constraint(None, 'ai_audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_ai_audit_logs_organization_id'), table_name='ai_audit_logs')
    op.drop_column('ai_audit_logs', 'organization_id')
    op.drop_index(op.f('ix_organization_memberships_user_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_organization_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_id'), table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
