"""create_ai_and_rag_tables

Revision ID: eeae576435ad
Revises: 5ac561c16a72
Create Date: 2026-09-08 14:56:14.711506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeae576435ad'
down_revision: Union[str, Sequence[str], None] = '5ac561c16a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('tool', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_audit_logs_id'), 'ai_audit_logs', ['id'], unique=False)
    op.create_table('ai_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_jobs_id'), 'ai_jobs', ['id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_id'), 'knowledge_documents', ['id'], unique=False)
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('training_date', sa.DateTime(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_registry_id'), 'model_registry', ['id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_id'), 'ai_conversations', ['id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_id'), 'ai_messages', ['id'], unique=False)
    op.add_column('ai_recommendations', sa.Column('agent_type', sa.String(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('reasoning_summary', sa.Text(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('supporting_data', sa.JSON(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('source_documents', sa.JSON(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('reviewed_by', sa.String(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.alter_column('ai_recommendations', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ai_recommendations', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('demand_forecasts', sa.Column('forecast_date', sa.DateTime(), nullable=False))
    op.add_column('demand_forecasts', sa.Column('horizon', sa.Integer(), nullable=False))
    op.add_column('demand_forecasts', sa.Column('predicted_quantity', sa.Float(), nullable=False))
    op.add_column('demand_forecasts', sa.Column('lower_bound', sa.Float(), nullable=False))
    op.add_column('demand_forecasts', sa.Column('upper_bound', sa.Float(), nullable=False))
    op.add_column('demand_forecasts', sa.Column('model_name', sa.String(), nullable=False))
    op.add_column('demand_forecasts', sa.Column('model_version', sa.String(), nullable=False))
    op.add_column('demand_forecasts', sa.Column('confidence', sa.Float(), nullable=True))
    op.alter_column('demand_forecasts', 'horizon_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('demand_forecasts', 'projected_demand',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('demand_forecasts', 'confidence_lower',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('demand_forecasts', 'confidence_upper',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demand_forecasts', 'confidence_upper',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('demand_forecasts', 'confidence_lower',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('demand_forecasts', 'projected_demand',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('demand_forecasts', 'horizon_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('demand_forecasts', 'confidence')
    op.drop_column('demand_forecasts', 'model_version')
    op.drop_column('demand_forecasts', 'model_name')
    op.drop_column('demand_forecasts', 'upper_bound')
    op.drop_column('demand_forecasts', 'lower_bound')
    op.drop_column('demand_forecasts', 'predicted_quantity')
    op.drop_column('demand_forecasts', 'horizon')
    op.drop_column('demand_forecasts', 'forecast_date')
    op.alter_column('ai_recommendations', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ai_recommendations', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('ai_recommendations', 'reviewed_at')
    op.drop_column('ai_recommendations', 'reviewed_by')
    op.drop_column('ai_recommendations', 'source_documents')
    op.drop_column('ai_recommendations', 'supporting_data')
    op.drop_column('ai_recommendations', 'reasoning_summary')
    op.drop_column('ai_recommendations', 'risk_score')
    op.drop_column('ai_recommendations', 'agent_type')
    op.drop_index(op.f('ix_ai_messages_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_ai_conversations_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_model_registry_id'), table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_index(op.f('ix_knowledge_documents_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_ai_jobs_id'), table_name='ai_jobs')
    op.drop_table('ai_jobs')
    op.drop_index(op.f('ix_ai_audit_logs_id'), table_name='ai_audit_logs')
    op.drop_table('ai_audit_logs')
    # ### end Alembic commands ###
