import React, { useState } from "react";
import AdminLayout from "./AdminLayout";
import RecommendationCard from "../../components/ai/RecommendationCard";
import { useRecommendations } from "../../hooks/useRecommendations";
import { Sparkles, CheckCircle2, ShieldCheck, Filter, RefreshCw } from "lucide-react";

export default function AdminRecommendations() {
  const [filterStatus, setFilterStatus] = useState("ALL");
  const { recommendations, loading, actionLoading, approve, reject, fetchRecommendations } = useRecommendations();

  const filtered = filterStatus === "ALL"
    ? recommendations
    : recommendations.filter(r => (r.status || "GENERATED").toUpperCase() === filterStatus);

  return (
    <AdminLayout
      title="AI Recommendations & Human-in-the-Loop Approval"
      subtitle="Autonomous procurement recommendations generated by multi-agent consensus. Purchase orders execute only upon administrator approval."
      onRefresh={fetchRecommendations}
      refreshing={loading}
    >
      <div className="space-y-6">
        {/* Status Filter Tabs */}
        <div className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            {[
              { id: "ALL", label: "All Records" },
              { id: "GENERATED", label: "Pending Review" },
              { id: "EXECUTED", label: "Executed POs" },
              { id: "REJECTED", label: "Rejected" },
            ].map((tab) => (
              <button
                key={tab.id}
                onClick={() => setFilterStatus(tab.id)}
                className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition cursor-pointer ${
                  filterStatus === tab.id
                    ? "bg-slate-950 text-white shadow-xs"
                    : "bg-white border border-slate-200 text-slate-600 hover:bg-slate-50"
                }`}
              >
                {tab.label}
              </button>
            ))}
          </div>

          <div className="text-xs text-slate-500 font-medium">
            Showing <strong className="text-slate-900 font-bold">{filtered.length}</strong> recommendations
          </div>
        </div>

        {/* Recommendations List */}
        <div className="space-y-4">
          {filtered.length === 0 ? (
            <div className="p-12 rounded-2xl border border-dashed border-slate-200 bg-white text-center">
              <ShieldCheck size={36} className="text-emerald-500 mx-auto mb-2" />
              <div className="text-sm font-bold text-slate-800 font-heading">
                No recommendations under '{filterStatus}' status
              </div>
              <p className="text-xs text-slate-500 mt-1">
                Run the Procurement Agent in AI Control Center to generate fresh restocking recommendations.
              </p>
            </div>
          ) : (
            filtered.map((rec) => (
              <RecommendationCard
                key={rec.id}
                recommendation={rec}
                onApprove={approve}
                onReject={reject}
                loading={actionLoading === rec.id}
              />
            ))
          )}
        </div>
      </div>
    </AdminLayout>
  );
}
